# Generated by Django 5.1.7 on 2025-11-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("PROCESSING", "Processing"),
                    ("SHIPPED", "Shipped"),
                    ("OUT_FOR_DELIVERY", "Out for Delivery"),
                    ("DELIVERED", "Delivered"),
                ],
                default="PROCESSING",
                max_length=50,
            ),
        ),
    ]
